
// Objective-C API for talking to the following Go packages
//
//	verification
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Verification_FRAMEWORK_H__
#define __Verification_FRAMEWORK_H__

#include "Verification.objc.h"
#include "Universe.objc.h"

#endif
