// Objective-C API for talking to verification Go package.
//   gobind -lang=objc verification
//
// File is generated by gobind. Do not edit.

#ifndef __Verification_H__
#define __Verification_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class VerificationAccountInfo;
@class VerificationVerify;

@interface VerificationAccountInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)privateKey;
- (NSString* _Nonnull)publicKey;
@end

@interface VerificationVerify : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)decrypt:(NSString* _Nullable)ct error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)decryptWithCheck:(NSString* _Nullable)account ct:(NSString* _Nullable)ct error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)encrypt:(NSString* _Nullable)plaintext error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)encryptBase64:(NSString* _Nullable)plaintext error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)encryptWithCheck:(NSString* _Nullable)account plaintext:(NSString* _Nullable)plaintext error:(NSError* _Nullable* _Nullable)error;
- (BOOL)verifyAccountWithPubKey:(NSString* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT VerificationAccountInfo* _Nullable VerificationGenerateKeyPair(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT VerificationVerify* _Nullable VerificationImportPrivKey(NSString* _Nullable key, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT VerificationVerify* _Nullable VerificationImportPubKey(NSString* _Nullable key, NSError* _Nullable* _Nullable error);

#endif
